apiVersion: v1
kind: Service
metadata:
  name: greet-arm
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  selector:
    app: greet-arm
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-arm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-arm
  template:
    metadata:
      labels:
        app: greet-arm
    spec:
      containers:
        - name: greet-arm
          image: nrt.ocir.io/orasejapan/shukawam/greet
          ports:
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
          imagePullPolicy: Always
      imagePullSecrets:
        - name: greet-secret
      nodeSelector: 
        beta.kubernetes.io/arch: arm64