apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/greet
  newName: nrt.ocir.io/orasejapan/shukawam/greet
  newTag: 7a71d0c096a8e6f98dc0ef672878e88d6aed88e0
namespace: multi-arch
